# Generated by Django 5.2.3 on 2025-06-15 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeassignment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='default@yahoo.com', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='default@yahoo.com', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='collectionschedule',
            name='customer',
            field=models.ForeignKey(default='default@yahoo.com', on_delete=django.db.models.deletion.CASCADE, to='myapp.customer'),
        ),
        migrations.AlterField(
            model_name='employeeassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee'),
        ),
        migrations.AlterField(
            model_name='extrapickuprequest',
            name='customer',
            field=models.ForeignKey(default='default@yahoo.com', on_delete=django.db.models.deletion.CASCADE, to='myapp.customer'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='Customer',
            field=models.ForeignKey(blank=True, default='default@yahoo.com', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='Customer',
            field=models.ForeignKey(default='default@yahoo.com', on_delete=django.db.models.deletion.CASCADE, to='myapp.customer'),
        ),
    ]
